### PR TITLE
fix path issue & json exception

### LINKED ISSUE #3: Arguments not working
When you set an argument and run it the first time the app is ran without the argument. In the second time it crashes Flow Launcher.

My settings:
Shortcut: n
Path: C:\WINDOWS\system32\notepad.exe
Arguments: c:\temp\file.txt

The behavior is consistent on my machine. It always crashes the second time.
I tried setting the description and/or work dir, it made no difference.

### LINKED ISSUE #9: System.Text.Json.JsonException
image

@taooceros Is this error related to the json change?

### PR DESCRIPTION
**Pull request by taooceros**
fix #9

### CODE REVIEW

**Review by jjw24 — CHANGES_REQUESTED** [review]
LGTM sorry for the delay. Just need to version bump.

**Comment by jjw24** [comment]
This should address #9 as well right?

**Review by jjw24 — APPROVED** [review]

**Comment by taooceros** [comment]
> This should address #9 as well right?

Yeah you are right.

**Comment by jjw24** [comment]
I m afk, will give u access if u want to release it now

**Comment by taooceros** [comment]
> I m afk, go ahead if u want to release it now

Ah I didn't see the message until now.🤣

**Pull request merged**
